export declare class TuiAnimation {
    aniConfig: UTSJSONObject;
    aniElement: UniElement;
    tranProperty: string[];
    styleProperty: UTSJSONObject;
    transformProperty: UTSJSONObject;
    isEventListener: boolean;
    isPlayAni: boolean;
    eventCallbackWrapper: any;
    transitionpropertyLength: number;
    constructor(dom: UniElement, config?: UTSJSONObject | null);
    animationQueue: UTSJSONObject[];
    aniCallback: () => void;
    removeEventListener(): void;
    aniEventListener: (e: UniEvent) => void;
    tranSitionEnd(callback: () => void): void;
    onTranSitionEnd(callback: () => void): void;
    playAnimation(): void;
    step(): TuiAnimation;
    export(): void;
    setAniProperty(prop: string, val: string): TuiAnimation;
    width(e: string): TuiAnimation;
    height(e: string): TuiAnimation;
    margin(e: string): TuiAnimation;
    marginTop(e: string): TuiAnimation;
    marginBottom(e: string): TuiAnimation;
    marginLeft(e: string): TuiAnimation;
    marginRight(e: string): TuiAnimation;
    left(e: string): TuiAnimation;
    right(e: string): TuiAnimation;
    top(e: string): TuiAnimation;
    bottom(e: string): TuiAnimation;
    padding(e: string): TuiAnimation;
    paddingLeft(e: string): TuiAnimation;
    paddingRight(e: string): TuiAnimation;
    paddingTop(e: string): TuiAnimation;
    paddingBottom(e: string): TuiAnimation;
    opacity(e: number): TuiAnimation;
    backgroundColor(e: string): TuiAnimation;
    borderColor(e: string): TuiAnimation;
    borderTopColor(e: string): TuiAnimation;
    borderBottomColor(e: string): TuiAnimation;
    borderLeftColor(e: string): TuiAnimation;
    borderRightColor(e: string): TuiAnimation;
    transformOrigin(e: string): TuiAnimation;
    duration(e: number): TuiAnimation;
    timingFunction(e: string): TuiAnimation;
    delay(e: number): TuiAnimation;
    setTransformProperty(prop: string, val: string): TuiAnimation;
    rotate(e: string): TuiAnimation;
    rotateX(e: string): TuiAnimation;
    rotateY(e: string): TuiAnimation;
    rotateZ(e: string): TuiAnimation;
    scale(e: string): TuiAnimation;
    scaleX(e: string): TuiAnimation;
    scaleY(e: string): TuiAnimation;
    translate(e: string): TuiAnimation;
    translateX(e: string): TuiAnimation;
    translateY(e: string): TuiAnimation;
}
